name: CNN Pipeline

on: 
  push:
    branches: 
      - master
  pull_request:
    branches: 
      - master

jobs:
  build-and-train:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      # DVC Setup and Data Pull
      - name: Set up DVC and pull data
        env:
          GDRIVE_CREDENTIALS_DATA: ${{ secrets.GDRIVE_CREDENTIALS_DATA }}
        run: |
          echo "${{ secrets.GDRIVE_CREDENTIALS_DATA }}" > credentials.json
          dvc remote modify --local gdrive-remote gdrive_service_account_json_file_path credentials.json
          dvc pull -v

      # Train or Test Model
      - name: Train Model
        run: |
          python main.py --mode train --data_path ./data/train/

      - name: Test Model
        run: |
          python main.py --mode test --data_path ./data/test/ --model_path ./models/checkpoint.pth
