name: CI workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      repository-projects: write
      id-token: write 
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'  # Adjust Python version if needed

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt 

      - name: Create Google Service Account JSON
        env:
          GDRIVE_CREDENTIALS_JSON: ${{ secrets.GDRIVE_CREDENTIALS_JSON }}  # Store full JSON as secret
        run: |
          echo "$GDRIVE_CREDENTIALS_JSON" > final-homework-446616-a6bbc08d73cc.json

      - name: DVC Pull Data
        run: |
          dvc remote modify --local gdrive-remote gdrive_service_account_json_file_path final-homework-446616-a6bbc08d73cc.json
          dvc pull -v 

      - name: Run Tests
        run: |
          mkdir -p plots
          python3 main.py --mode test --data_path ./data/test/ --model_path ./models/cnn_resnet18_freeze_backbone_False.pth
