name: CI Workflow

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      repository-projects: write
      id-token: write

    steps:
      # Checkout the repository code
      - name: Checkout repository
        uses: actions/checkout@v2

      # Install uv (Universal Viewer) CLI, similar to conda
      - name: Install uv
        uses: astral-sh/setup-uv@v2

      # Set up Python environment with a newer version
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # DVC: Create credentials.json
      - name: Create credentials.json
        env:
          GDRIVE_CREDENTIALS_DATA: ${{ secrets.GDRIVE_CREDENTIALS_DATA }}
        run: echo "$GDRIVE_CREDENTIALS_DATA" > credentials.json

      # Modify DVC Remote
      - name: Add DVC Remote for GDrive
        run: |
          uv run dvc remote modify --local gdrive_remote gdrive_service_account_json_file_path credentials.json

      # DVC Pull Data
      - name: DVC Pull Data
        run: |
          uv run dvc pull -v

      # Run CNN Ship Filter Inference
      - name: Set up MLflow tracking URI
        env:
          MLFLOW_TRACKING_URI: ${{ secrets.MLFLOW_TRACKING_URI }}
        run: |
          echo "MLFLOW_TRACKING_URI=${{ secrets.MLFLOW_TRACKING_URI }}"

      - name: Run Training with MLflow Experiment Logging
        run: |
          mkdir -p /home/runner/work/classification-pytorch/classification-pytorch/plots
          python3 src/train.py --epochs 20 --batch_size 8 --learning_rate 0.001 --model_dir ./models --plot_dir ./plots --backbone resnet18 --freeze_backbone True
          python3 src/train.py --epochs 20 --batch_size 16 --learning_rate 0.001 --model_dir ./models --plot_dir ./plots --backbone resnet18 --freeze_backbone True
          python3 src/train.py --epochs 25 --batch_size 16 --learning_rate 0.001 --model_dir ./models --plot_dir ./plots --backbone resnet18 --freeze_backbone True

      # Upload the MLflow experiment results using the latest version of the action
      - name: Upload the MLflow experiment results
        uses: actions/upload-artifact@v3
        with:
          name: mlflow-experiment-results
          path: ./mlruns  # Adjust path as needed to where MLflow logs are stored

      - name: Run Inference (Test) on Best Model
        run: |
          mkdir -p /home/runner/work/classification-pytorch/classification-pytorch/plots
          python3 src/main.py --mode test --data_path ./data/test/ --model_path ./models/cnn_resnet18_freeze_backbone_True.pth
